name: js-custom

on: [push]
#   schedule:
#   - cron: "0 0 * * *" # triggers every midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install node dependencies
      run: npm install
    - name: Hello world action step
      id: hello
      with:
          who-to-greet: 'Myself'
